# src/iamp_optimizer/main.py

# We need to adjust the Python path to make imports work correctly
# when running this script directly from the project root.
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

# Now we can use absolute imports from the package root
from src.iamp_optimizer.models.waypoint import Waypoint
from src.iamp_optimizer.models.flight_path import FlightPath
from src.iamp_optimizer.ui.visualization import plot_path

def run_step_1():
    """
    Executes the first-step 'dumb path' functionality.
    Creates a simple straight-line path and visualizes it.
    """
    print("Running IAMP Static Optimizer - Step 1: 'Dumb Path' Visualization")
    
    # 1. Define the mission start and end points
    start_point = Waypoint(x=10, y=10)
    end_point = Waypoint(x=90, y=80)
    
    # 2. Create the simplest possible flight path (a straight line)
    #    In the future, this path will be generated by our Genetic Algorithm.
    simple_flight_path = FlightPath(waypoints=[start_point, end_point])
    
    print(f"Created a simple {simple_flight_path}")
    print(f"Start: {start_point}, End: {end_point}")
    
    # 3. Visualize the path
    plot_path(simple_flight_path, title="Step 1: Simple Straight-Line Path")

if __name__ == "__main__":
    run_step_1()